id: P010547
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:23.291840
source_metadata:
  id: bdr:W20184
  title: བོད་ཀྱི་ལྷ་སྒྲུང་སྐོར་གླེང་བ
  author: ''
  volumes:
    d8a8fbade83149f1a2105b0a127e2cff:
      image_group_id: I4991
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
