id: ID09D4D15
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:06:01+00:00'
last_modified: '2022-06-08T14:24:18.738667+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20184
  title: བོད་ཀྱི་ལྷ་སྒྲུང་སྐོར་གླེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F8DE:
      image_group_id: I4991
      title: ''
      total_pages: 134
      order: 1
      base_file: F8DE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
